version: "3.7"
services:
  spark-master:
    image: spark-hadoop-cluster-slim:latest
    container_name: spark-master
    hostname: spark-master
    tty: true
    volumes:
      - ../../../projects:/user_data
      - /home/hadoop:/hadoop_data
      - vol1:/csvs
    ports:
      - "8088:8088" # ResourceManager
      - "9870:9870" # NameNode WebUI
      - "10015:10015" # HDFS
      - "8080:8080" # WebUI Spark Master
      - "18080:18080" # History WebUI Spark Master
      - "8042:8042" # NodeManager
      - "8888:8888" # Jupyter
      - "4040:4040" # Spark
      - "10000:10000" # HiveServer2 - Binary Mode
      - "10001:10001" # HiveServer - HTTP Mode
      - "10002:10002" # Hiveserver WebUI
      - "9083:9083" # Hive Metastore
      - "9092:9092" # Kafka
    networks:
      cluster-network:
        ipv4_address: 10.5.0.2
    environment:
      - "SPARK_LOCAL_IP=spark-master"
    deploy:
      placement:
        constraints: [node.role == manager]
  spark-worker-1:
    image: spark-hadoop-cluster-slim:latest
    container_name: spark-worker-1
    hostname: spark-worker-1
    tty: true
    volumes:
      - /home/hadoop:/hadoop_data
      - vol1:/csvs
    depends_on:
      - spark-master
    ports:
      - "8081:8081" # WebUI Spark worker
      - "6042:8042" # NodeManager
    environment:
      - "SPARK_LOCAL_IP=spark-worker-1"
    networks:
      cluster-network:
        ipv4_address: 10.5.0.3
    deploy:
      placement:
        constraints:
          - node.labels.workerid == 1
  spark-worker-2:
    image: spark-hadoop-cluster-slim:latest
    container_name: spark-worker-2
    hostname: spark-worker-2
    tty: true
    volumes:
      - /home/hadoop:/hadoop_data
      - vol1:/csvs
    depends_on:
      - spark-master
    ports:
      - "8082:8081" # WebUI Spark worker
      - "7042:8042" # NodeManager
    environment:
      - "SPARK_LOCAL_IP=spark-worker-2"
    networks:
      cluster-network:
        ipv4_address: 10.5.0.4
    deploy:
      placement:
        constraints:
          - node.labels.workerid == 2
networks:
  cluster-network:
    driver: overlay
    attachable: true
    ipam:
     driver: default
     config:
       - subnet: 10.5.0.0/16
volumes:
  vol1:
    driver: glustermochhoa
    name: "staging-gfs"