version: "3.7"
services:
  spark-master:
    image: spark-hadoop-cluster:latest
    container_name: spark-master
    hostname: spark-master
    tty: true
    volumes:
      - /home/ubuntu/projects:/user_data
      - /media/data/hadoop:/hadoop_data
      - etl_data:/glustervol1
    ports:
      - "8088:8088" # ResourceManager
      - "9870:9870" # NameNode WebUI
      - "10015:10015" # HDFS
      - "8080:8080" # WebUI Spark Master
      - "18080:18080" # History WebUI Spark Master
      - "8042:8042" # NodeManager
      - "4040:4040" # Spark
    networks:
      cluster-network:
        ipv4_address: 10.5.0.2
    environment:
      - "SPARK_LOCAL_IP=spark-master"
    deploy:
      placement:
        constraints:
          - node.labels.workerid == 1
    extra_hosts:
      - "spark:10.5.0.2"
  spark-worker-1:
    image: spark-hadoop-cluster:latest
    container_name: spark-worker-1
    hostname: spark-worker-1
    tty: true
    volumes:
      - /media/data/hadoop:/hadoop_data
      - etl_data:/glustervol1
    depends_on:
      - spark-master
    ports:
      - "8081:8081" # WebUI Spark worker
      - "6042:8042" # NodeManager
      - "8088:8088" # ResourceManager
    environment:
      - "SPARK_LOCAL_IP=spark-worker-1"
      - "SPARK_WORKER_WEBUI_PORT=8088"
    networks:
      cluster-network:
        ipv4_address: 10.5.0.3
    deploy:
      placement:
        constraints:
          - node.labels.workerid == 2
  spark-worker-2:
    image: spark-hadoop-cluster:latest
    container_name: spark-worker-2
    hostname: spark-worker-2
    tty: true
    volumes:
      - /media/data/hadoop:/hadoop_data
      - etl_data:/glustervol1
    depends_on:
      - spark-master
    ports:
      - "8082:8081" # WebUI Spark worker
      - "7042:8042" # NodeManager
      - "8088:8088" # ResourceManager
    environment:
      - "SPARK_LOCAL_IP=spark-worker-2"
      - "SPARK_WORKER_WEBUI_PORT=8088"
    networks:
      cluster-network:
        ipv4_address: 10.5.0.4
    deploy:
      placement:
        constraints: [node.role == manager]
  hive-server:
    image: hive-server:latest
    container_name: hive-server
    hostname: hive-server
    tty: true
    volumes:
      - /media/data/hadoop:/hadoop_data
    ports:
      - "10000:10000" # HiveServer2 - Binary Mode
      - "10001:10001" # HiveServer - HTTP Mode
      - "10002:10002" # Hiveserver WebUI
      - "9083:9083" # Hive Metastore
      - "3306:3306" # MySQL
    networks:
      cluster-network:
        ipv4_address: 10.5.0.5
    deploy:
      placement:
        constraints:
          - node.labels.workerid == 1
  jupyter:
    image: jupyter:latest
    container_name: jupyter
    hostname: jupyter
    tty: true
    volumes:
      - /home/ubuntu/projects:/user_data
      - /media/data/hadoop:/hadoop_data
      - etl_data:/glustervol1
    ports:
      - "8888:8888" # Jupyter
    networks:
      cluster-network:
        ipv4_address: 10.5.0.6
    deploy:
      placement:
        constraints:
          - node.labels.workerid == 2
networks:
  cluster-network:
    driver: overlay
    attachable: true
    ipam:
     driver: default
     config:
       - subnet: 10.5.0.0/16
volumes:
  etl_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/vol1